environment:
    arch: i686
    WIDTH: 32
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: atomlong
    BINTRAY_REPOSITORY: msys2
    BINTRAY_API_KEY:
        secure: 7Y8ikRknA3WY2ZtJJQy8RHYp6UOh8t70h2vvIQTC1voX0nAltZRKcfy6Z/gWzY9D
    BINTRAY_VERSION: latest
    PACMAN_REPOSITORY_NAME: msys
    DISTRIB_PACKAGE_NAME: distrib
    GPG_KEY_PASSWD:
        secure: DVuRK/wrA/hczYhh65X1WA==
    GPG_FILE_SECRET:
        secure: 4OO2rdWNRtdaJiS8aPotGQ==
    MSYS2_ROOT: C:\msys%WIDTH%
    DISTRIB_FILE_URL: https://dl.bintray.com/%BINTRAY_ACCOUNT%/%BINTRAY_REPOSITORY%/%DISTRIB_PACKAGE_NAME%/%arch%/msys2-base-%arch%-latest.tar.xz
    DISTRIB_FILE_NAME: msys2-base-%arch%-latest.tar.xz   
    CI_NAME: appveyor
    CI_REPO: $(APPVEYOR_REPO_NAME)
    CI_BRANCH: $(APPVEYOR_REPO_BRANCH)
    CI_BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
    CI_JOB_NUMBER: $(APPVEYOR_JOB_NUMBER)
    CI_BUILD_DIR: $(APPVEYOR_BUILD_FOLDER)
    CI_BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)

cache:
    - C:\msys%WIDTH%-build

install:
    - install.cmd

build_script:
    - C:\msys%WIDTH%-build\usr\bin\bash --login -c "$(cygpath ${CI_BUILD_DIR})/ci-build.sh BUILD"

after_build:
    - C:\msys%WIDTH%-build\usr\bin\bash --login -c "$(cygpath ${CI_BUILD_DIR})/ci-build.sh DISTRIB"

deploy_script:
    - C:\msys%WIDTH%-build\usr\bin\bash --login -c "$(cygpath ${CI_BUILD_DIR})/ci-build.sh DEPLOY"

after_deploy:
    - C:\msys%WIDTH%-build\usr\bin\bash --login -c "$(cygpath ${CI_BUILD_DIR})/ci-build.sh CACHE"

