environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: atomlong
    BINTRAY_REPOSITORY: msys2
    BINTRAY_API_KEY:
        secure: 7Y8ikRknA3WY2ZtJJQy8RHYp6UOh8t70h2vvIQTC1voX0nAltZRKcfy6Z/gWzY9D
    BINTRAY_VERSION: latest
    PACMAN_REPOSITORY_NAME: msys
    DISTRIB_PACKAGE_NAME: distrib
    GPG_KEY_PASSWD:
        secure: DVuRK/wrA/hczYhh65X1WA==
    GPG_FILE_SECRET:
        secure: HvVAsdbdYQGzdOUefe2VlQ==
    arch: i686
    MSYS2_ROOT: C:\msys32
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)

install:
    - curl -fsSL -o msys2-base-i686-latest.tar.xz https://dl.bintray.com/%BINTRAY_ACCOUNT%/%BINTRAY_REPOSITORY%/%DISTRIB_PACKAGE_NAME%/%arch%/msys2-base-i686-latest.tar.xz
    - C:\cygwin\bin\bash --login -c "cd \"%CD%\"; rm -rf /cygdrive/c/msys32; tar -xf msys2-base-i686-latest.tar.xz -C /cygdrive/c/; mv -vf /cygdrive/c/msys32{,-build}"
    - C:\msys32-build\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh INSTALL"

build_script:
    - C:\msys32-build\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys32-build\usr\bin\pacman --noconfirm --sync --needed base-devel msys2-devel git
    - C:\msys32-build\autorebase.bat
    - C:\msys32-build\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh BUILD"

after_build:
    - C:\msys32-build\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh  DISTRIB"

deploy_script:
    - C:\msys32-build\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh  DEPLOY"
